trigger:
  - main
pool:
  name: news
  vmImage: ubuntu-latest

stages:
  - stage: "This is my first stage"
    jobs:
      - job: "Firstjob"
        steps:
          - script: echo "This is my Linux Os"